---
 - name: set MacOS specific parameters
   set_fact:
      device_separator: s
      device_prefix: r
      mount_location: /Volumes/bootfs
   when: ansible_distribution == 'MacOSX'

 - name: unmount boot volume on MacOS
   command: "diskutil unmount /dev/{{ device_prefix }}{{ device_name }}{{ device_separator}}1"
   when: ansible_distribution == 'MacOSX'

 - name: copy image to SD card
   command: dd if={{ image_path }} of=/dev/{{ device_name }} bs=4194304
   when: copy_image == 'yes'

 - name: copy custom.toml file to boot partition
   template:
      src: custom.toml
      dest: "{{ mount_location }}/custom.toml"
